server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/products/**
        - id: ms-authorization
          uri: lb://ms-authorization
          predicates:
            - Path=/users/**, /oauth/**
        - id: ms-notifications
          uri: lb://ms-notifications
          predicates:
            - Path=/notification/**

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: false
#logging:
#  level:
#    root: debug
#    org.springframework.cloud.netflix.eureka: debug